### ISSUE TITLE
[1.x][RFC] refactor whole model configuration

### ISSUE THREAD

**Issue by Ma27** [Ma27/Ma27ApiKeyAuthenticationBundle#30]
## Status quo

Currently it is necessary to adjust parameters such as "username_prop" or "password_prop" in order to gather model properties for doctrine related operations.
As the ApiKeyPurger requires more properties, we end up in a configuration hell using this approach.
## Idea

Instead, annotations can be used in order to configure the model properly.

``` php
use Ma27\ApiKeyAuthenticationBundle\Annotation as Auth;
use Symfony\Component\Security\...\UserInterface;

class User implements UserInterface
{
    /** @Auth\Login*/
    private $username;
    /** @Auth\Password */
    private $password;
}
```

Then it is necessary to adjust the class name and the manager service and everything works.
### Email authentication

In this case it is simply necessary to create an email property and assign the annotation "@Auth\Login" to the email property

**Comment by benbieler** [comment]
I think this is a great idea! :+1:
