### ISSUE TITLE
Custom hasher does not work

### ISSUE THREAD

**Issue by buiminhduc** [Ma27/Ma27ApiKeyAuthenticationBundle#57]
### Description

I'm using this bundle with FOSUser bundle, and need to use custom hasher, but it does not work
### Steps to reproduce

Create custom hasher
Add config as the document
Try, to get API key, but got error: Invalid password strategy "custom". Allowed strategies are "password", "crypt", "sha512", "phpass"!
### Expected behavior

Custom hasher should be able to use
### Further details

I'm using Symfony 2.8

**Comment by Ma27** [comment]
ok, seems to be fixed on master. Will try to release something today :)

**Comment by buiminhduc** [comment]
Thank you!  :)
Regards
Duc

**Comment by Ma27** [comment]
https://github.com/Ma27/Ma27ApiKeyAuthenticationBundle/blob/master/Tests/DependencyInjection/ConfigurationTest.php#L45-L66 should fix now

**Comment by Ma27** [comment]
will wait for CI services, then tag the release :)

**Comment by Ma27** [comment]
https://github.com/Ma27/Ma27ApiKeyAuthenticationBundle/releases/tag/1.2.0
